# Generated by Django 5.1.1 on 2024-10-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_pedidos_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='fecha',
        ),
    ]
