# Generated by Django 5.1.1 on 2024-10-10 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_remove_pedidos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
